<?php

function hello_menu_menu() {
  $items = array();
  
  $items['hello'] = array(
    //this automagically goes through the t function
    'title' => 'Hello World',
    'page callback' =>'hello_menu_simple_hello',
    'access arguments' => array('access content'),
    'menu_name' => 'main-menu',
    'weight' => 1,
  );
  
  return $items;
}

function hello_menu_simple_hello() {
  return t('Hello Worlder');
}